package no.javaspill.data;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import no.javaspill.model.*;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;

/**
 * Generates /public/js/courseData.js from the Java course data.
 * This file is used by the Android WebView version (offline mode).
 */
public class CourseDataExporter {

    public static void export() {
        try {
            List<CourseModule> modules = CourseData.getModules();
            ObjectMapper mapper = new ObjectMapper();
            mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);

            // ── Module summaries (for home/module views) ──
            List<Map<String, Object>> moduleSummaries = new ArrayList<>();
            for (CourseModule m : modules) {
                Map<String, Object> summary = new LinkedHashMap<>();
                summary.put("id",          m.getId());
                summary.put("title",       m.getTitle());
                summary.put("description", m.getDescription());
                summary.put("icon",        m.getIcon());
                summary.put("color",       m.getColor());
                summary.put("available",   m.isAvailable());
                summary.put("lessonCount", m.getLessons().size());

                List<Map<String, Object>> lessonSummaries = new ArrayList<>();
                for (Lesson l : m.getLessons()) {
                    Map<String, Object> ls = new LinkedHashMap<>();
                    ls.put("id",            l.getId());
                    ls.put("title",         l.getTitle());
                    ls.put("exerciseCount", l.getExercises().size());
                    lessonSummaries.add(ls);
                }
                summary.put("lessons", lessonSummaries);
                moduleSummaries.add(summary);
            }

            // ── Full lessons indexed by id ──
            Map<String, Object> lessonsById = new LinkedHashMap<>();
            for (CourseModule m : modules) {
                for (Lesson l : m.getLessons()) {
                    // Build a clean map so we control the keys
                    Map<String, Object> lessonMap = new LinkedHashMap<>();
                    lessonMap.put("id",               l.getId());
                    lessonMap.put("moduleId",         l.getModuleId());
                    lessonMap.put("title",            l.getTitle());
                    lessonMap.put("guideContent",     l.getGuideContent());
                    lessonMap.put("codeExampleTitle", l.getCodeExampleTitle());
                    lessonMap.put("codeExample",      l.getCodeExample());

                    List<Map<String, Object>> exList = new ArrayList<>();
                    for (Exercise ex : l.getExercises()) {
                        Map<String, Object> exMap = new LinkedHashMap<>();
                        exMap.put("id",                ex.getId());
                        exMap.put("type",              ex.getType().name());
                        exMap.put("question",          ex.getQuestion());
                        exMap.put("hint",              ex.getHint());
                        exMap.put("correctFeedback",   ex.getCorrectFeedback());
                        exMap.put("incorrectFeedback", ex.getIncorrectFeedback());
                        exMap.put("explanation",       ex.getExplanation());
                        exMap.put("solutionCode",      ex.getSolutionCode());
                        // MC fields
                        exMap.put("options",           ex.getOptions());
                        exMap.put("correctOptionIndex",ex.getCorrectOptionIndex());
                        // Code fields
                        exMap.put("codeTemplate",      ex.getCodeTemplate());
                        exMap.put("requiredPatterns",  ex.getRequiredPatterns());
                        exList.add(exMap);
                    }
                    lessonMap.put("exercises", exList);
                    lessonsById.put(String.valueOf(l.getId()), lessonMap);
                }
            }

            Map<String, Object> courseData = new LinkedHashMap<>();
            courseData.put("modules", moduleSummaries);
            courseData.put("lessons", lessonsById);

            String json = mapper.writeValueAsString(courseData);
            String js   = "/* Auto-generated by CourseDataExporter – do not edit manually */\n"
                        + "window.COURSE_DATA = " + json + ";\n";

            // Write to the public JS folder
            Path outPath = Paths.get("src/main/resources/public/js/courseData.js");
            Files.writeString(outPath, js);

            int lessonCount = lessonsById.size();
            System.out.println("✅ courseData.js generert – "
                + modules.size() + " moduler, "
                + lessonCount + " leksjoner");

        } catch (IOException e) {
            System.err.println("⚠️  Feil ved generering av courseData.js: " + e.getMessage());
        }
    }
}
